<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>Spooler_universal</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibUsbDotNet" Version="2.2.29" />
    <PackageReference Include="System.Management" Version="5.0.0" />
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
    <PackageReference Include="System.Device.Gpio" Version="3.2.0" />


  </ItemGroup>

</Project>